import { z } from "zod";

export const schemaMaster = z
    .object({
        no_nas: z.string(),
        nm_nas: z.string(),
        tipe_nas: z.number(),
        kd_jns_ident: z.number(),
        no_ident: z.string(),
        masa_ident: z.number(),
        tgl_ident: z.string().datetime().optional(),
        kd_acc_off: z.string(),
        kd_bntk_hkm: z.number(),
        kd_gol_pemilik: z.number(),
        flag_hub_bank: z.boolean(),
        kd_sumber_dana: z.number(),
        kd_tujuan_dana: z.number(),
        kd_maks_trans: z.number(),
        kd_penghasilan_bulan: z.number(),
        kd_penghasilan_lainnya: z.number().optional(),
        kd_pengeluaran_bulan: z.number(),
        kd_pengeluaran_lainnya: z.number().optional(),
        npwp: z.string(),
        no_telp: z.string(),
        email: z.string(),
        kd_bidang_usaha: z.union([z.number(), z.null()]).optional(),
        usrid_create: z.string(),
    })
    .required({
        created_at_kantor: true,
        nm_nas: true,
        tipe_nas: true,
        kd_jns_ident: true,
        no_ident: true,
        masa_ident: true,
        kd_acc_off: true,
        kd_bntk_hkm: true,
        kd_gol_pemilik: true,
        flag_hub_bank: true,
        kd_sumber_dana: true,
        kd_tujuan_dana: true,
        kd_maks_trans: true,
        kd_penghasilan_bulan: true,
        kd_pengeluaran_bulan: true,
        npwp: true,
        no_telp: true,
        email: true,
        usrid_create: true,
    });
